### ISSUE TITLE
希望TD也可以加入AIP运动

### ISSUE THREAD

**Issue by yqs112358** [hhhxiao/TrapDoor#26]
我们的目的旨在为BDS插件开发圈做一个简单的整合运动
AIP 全称 All in plugins ，为了解决BDS目录树的复杂混乱而生。
相关介绍可见 https://www.minebbs.com/threads/all-in-plugins-aip-bds.6350/
希望trapdoor相关的配置文件可以存放到plugins/trapdoor中，日志输出可以统一安排到logs中。
小小的改变可以给服务器升级与迁移带来很大的便利
欢迎您的参与！

**Comment by hhhxiao** [comment]
好家伙，可

**Comment by hhhxiao** [comment]
dbcf98d5a52b02148e804f92615c31ee7555ec28

**Comment by yqs112358** [comment]
It's great!
