### ISSUE TITLE
请求适配1.16.210

### ISSUE THREAD

**Issue by yqs112358** [hhhxiao/TrapDoor#27]
这个版本进行了较大的性能优化，希望TD也可以尽早适配
同时宣传一下下面的AIP =w=

**Comment by hhhxiao** [comment]
咕咕咕

**Comment by yqs112358** [comment]
呜呜呜

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/TrapDoor/releases/tag/trapdoor-0.9.42-1.16.210.06-test

**Comment by yqs112358** [comment]
啊这
如何编译
没看到sln也没看到makefile

**Comment by hhhxiao** [comment]
看这里[https://github.com/hhhxiao/TrapDoor/wiki/5.-%E5%BC%80%E5%8F%91](https://github.com/hhhxiao/TrapDoor/wiki/5.-%E5%BC%80%E5%8F%91)
第一个cmake命令在`build`目录下编译生成vs工程，第二个命令编译这个工程

**Comment by yqs112358** [comment]
OKOK编译完了
多谢

**Comment by yqs112358** [comment]
等等 文件名编译出来是trapdoor-0.9.42-1.16.40.2.dll
这合理吗

**Comment by yqs112358** [comment]
而且那个config文件不知在何处
启动提示
can't find the language dictionary
can not read config file trapdoor-config.json 
can not read configFile, trapdoor won't be injected
然后started.之后就崩服了

**Comment by hhhxiao** [comment]
下载下来的源码默认是1.16.4的，你要切换到210的分支，配置文件去release里面下载

**Comment by yqs112358** [comment]
行吧行吧

**Comment by yqs112358** [comment]
多谢了
