### ISSUE TITLE
Custom Blocks

### ISSUE THREAD

**Issue by Lamfi** [hhhxiao/TrapDoor#3]
How to create custom block on C++ I triyng to use BlockTypeRegistry::registerBlocks but u have crashes

**Comment by Lamfi** [comment]
How to create cusom block , i have trouble with this,can you give example?

**Comment by hhhxiao** [comment]
I am sorry, I have no plan to support custom block,  every time I add an api to this project，I neet to take much time to test it.

**Comment by 0x506978656c** [comment]
Another thing to take note is that this is mainly intended for the more technical areas of Minecraft Bedrock. 
I feel that this request is sided more to the general concept of modding. With that being said, I would recommend you look more into the [MCMODDLL-CPP](https://github.com/zhkj-liuxiaohua/MCMODDLL-CPP) which can be found at the link there \o/

Hope this helps >_<

**Comment by hhhxiao** [comment]
> Another thing to take note is that this is mainly intended for the more technical areas of Minecraft Bedrock.
> I feel that this request is sided more to the general concept of modding. With that being said, I would recommend you look more into the [MCMODDLL-CPP](https://github.com/zhkj-liuxiaohua/MCMODDLL-CPP) which can be found at the link there \o/
> 
> Hope this helps >_<

Thank you,but so far the development direction  of trapdoor is not a general mod api ,I just want to write a mod like carpet

**Comment by 0x506978656c** [comment]
Sry if I wasn't clear but that's what I was saying xD
