### ISSUE TITLE
Nether fortress spawning spots not showing up

### ISSUE THREAD

**Issue by counterfitninja** [hhhxiao/TrapDoor#30]
I have enabled HSA on my world and Witch huts and Guardian spawning spots show up, but Nether fortress spawn spots do not seem to be showing up.

Impressive hack though.

**Comment by hhhxiao** [comment]
What's your game version?

**Comment by counterfitninja** [comment]
It's the latest version 1.16.210

**Comment by hhhxiao** [comment]
repair in  35ade085046fda7c6bc89516da2ac9fad45914e3
release in [https://github.com/hhhxiao/TrapDoor/releases/tag/0.9.42-1.16.210.06-test2](https://github.com/hhhxiao/TrapDoor/releases/tag/0.9.42-1.16.210.06-test2)
thanks for you report
