### ISSUE TITLE
Add 1.17.2.01 Support

### ISSUE THREAD

**Issue by 1shin-7** [hhhxiao/TrapDoor#47]
我尝试在基岩服务器版本1.17.2.01注入这个DLL，但是它[崩溃了](https://paste.ubuntu.com/p/GB5nNcGxvr/)

**Comment by hhhxiao** [comment]
1.17.2在做了在做了

**Comment by 1shin-7** [comment]
好耶！
~~我先去玩原神了~~

**Comment by 1shin-7** [comment]
催个更qwq

**Comment by hhhxiao** [comment]
听说马上要更新新版本了，等下个新版出来再更吧

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/TrapDoor/releases/tag/0.9.6-1.17.10.04 
更了1.17.10.04，.2不做了
