### ISSUE TITLE
Crash when use /village v true

### ISSUE THREAD

**Issue by EternityXuNuo** [hhhxiao/TrapDoor#48]
In the release "0.9.50-symdb-1.17.1.01",when I use /village v ture ,it crash

**Comment by hhhxiao** [comment]
mojang modifies village's data structure and disable the symbols of Linux version，which cause this function can not work，i will disable this command in next version and repair it after mojang add symbols back to Linux bds，thanks for you feedback.

**Comment by Redbeanw44602** [comment]
In 1.17.10.04, Mojang provided symbol files and I am looking forward to the restoration of this function.

**Comment by hhhxiao** [comment]
repair in f7bb60aaf7bfe87866e1dcc163c176edd39af1c6, donwload it at https://github.com/hhhxiao/TrapDoor/releases/tag/0.9.6-1.17.10.04
