### ISSUE TITLE
Hook interface conflicts

### ISSUE THREAD

**Issue by EternityXuNuo** [hhhxiao/TrapDoor#49]
it seems that there will be conflicts if i  use both _trapdoor_(which supports 1.17.1.01 version) and _liteloader_
and it seems "hook interface conflicts"

**There is error code**
`[!] Hook error at Hook: DetourAttach Error : MSSYM_MD5_3b8fb7204bf8294ee636ba7272eec000
[!] Hook error at Hook: DetourTransactionBegin Error : MSSYM_B1QA5useOnB1AA4ItemB2AAA4QEBAB1UE14NAEAVItemStackB2AAA9AEAVActorB2AAA7HHHEMMMB1AA1Z
[!] Hook error at Hook: DetourTransactionBegin Error : MSSYM_MD5_8574de98358ff66b5a913417f44dd706
[!] Hook error at Hook: DetourTransactionBegin Error : MSSYM_B1QA6handleB1AE20ServerNetworkHandlerB2AAE26UEAAXAEBVNetworkIdentifierB2AAE24AEBVCommandRequestPacketB3AAAA1Z`

**Comment by hhhxiao** [comment]
这个是没办法的，tr为了保持独立性，必然和某些库有一些冲突，没法解决
