### ISSUE TITLE
与1.17.11不兼容

### ISSUE THREAD

**Issue by Redbeanw44602** [hhhxiao/TrapDoor#53]
1.17.11.01已经更新，希望作者尽快适配~

另外为何不考虑一下LiteLoader的SymDB方案呢，小版本大概率自动适配了🤔

**Comment by hhhxiao** [comment]
他们那边文档不完善，我用ll的方案还得自己去官方仓库扒代码

**Comment by hhhxiao** [comment]
1.17.11.01应该已经支持了，下载该分支的源码编译即可，暂时没有release
