### ISSUE TITLE
Problems when i want inject trapdoor on a hosted cloud server

### ISSUE THREAD

**Issue by alanreypato** [hhhxiao/TrapDoor#55]
I was researching and talking to people who have used hatch and they all tell me they use it in a Local BDS, they also told me that it was not possible to inject it into a server hosted in the cloud, if the problem is, it can be injected into a server hosted in the cloud (I've been trying with an FTP Program and I don't know if it can be done)

**Comment by hhhxiao** [comment]
What does "server hosted in the cloud" means ? What is your authority to this server?

**Comment by alanreypato** [comment]
We are using a server hosting service called Shockbyte, and my position on that server is owner

**Comment by hhhxiao** [comment]
If you have the permission to upload files and use powershell,or run any executable file, you can do it

**Comment by alanreypato** [comment]
ok, i will try
