### ISSUE TITLE
注入成功了，进去服务器里一个命令也用不了

### ISSUE THREAD

**Issue by snfcx** [hhhxiao/TrapDoor#57]
命令提示不存在，版本1.17.11.01
![image](https://user-images.githubusercontent.com/55078254/132953363-604b9b37-44ea-4d8f-b719-b865d05978ec.png)
![image](https://user-images.githubusercontent.com/55078254/132953396-5ac8377c-3971-45e1-8110-423191a875d4.png)

**Comment by hhhxiao** [comment]
你这日志信息不完整，最后一行有输出 `trapdoor finish, server started`吗

**Comment by snfcx** [comment]
![image](https://user-images.githubusercontent.com/55078254/132955058-b33420a8-4db7-4eb6-8874-89fb1158af11.png)
最后输出的

**Comment by hhhxiao** [comment]
那说明没有注入成功

**Comment by hhhxiao** [comment]
正常的是这样的
```
Active code page: 65001
TRAPDOOR LOGGER INIT

  _______                  _
 |__   __|                | |
    | |_ __ __ _ _ __   __| | ___   ___  _ __
    | | '__/ _` | '_ \ / _` |/ _ \ / _ \| '__|
    | | | | (_| | |_) | (_| | (_) | (_) | |
    |_|_|  \__,_| .__/ \__,_|\___/ \___/|_|
                | |
                |_|

github:https://github.com/hhhxiao/TrapDoor
License: GPL
trapdoor version: 0.9.73-1.17.11.01-test
build time:     Sep  3 2021      12:33:27
-----------------------------------------------
begin read config file plugins/trapdoor/trapdoor-config.json
read config file plugins/trapdoor/trapdoor-config.json successfully

begin read EULA
read eula success
begin read command permission info
 - /apicfg    enable:1  level:1
 - /backup    enable:1  level:1
 - /c         enable:1  level:1
 - /cl        enable:1  level:0
 - /counter   enable:1  level:1
 - /dev       enable:1  level:1
 - /draw      enable:1  level:0
 - /fakeplayer enable:1  level:1
 - /func      enable:1  level:1
 - /here      enable:1  level:0
 - /hsa       enable:1  level:0
 - /l         enable:1  level:1
 - /lang      enable:1  level:1
 - /mspt      enable:1  level:0
 - /o         enable:1  level:1
 - /os        enable:1  level:0
 - /prof      enable:1  level:0
 - /rs        enable:1  level:1
 - /s         enable:1  level:1
 - /self      enable:1  level:0
 - /slime     enable:1  level:0
 - /spawn     enable:1  level:0
 - /td?       enable:1  level:0
 - /tick      enable:1  level:1
 - /village   enable:1  level:0
read command permission info successfully

begin read low level vanilla command info
here are the all low level commands:
- stop
- whitelist
read low level vanilla commands successfully

begin read server info
 - levelMame : Bedrock level
read server info successfully

begin read village config info
 - bound color: red
 - spawn color: red
 - poiQueryColor: red
 - center:minecraft:heart_particle
read village color successfully

begin read function config
read function config successfully

begin read self command config
read self command config successfully

create BDS mod instance
NO LOG FILE! - setting up server logging...
[2021-09-03 22:07:11 INFO] Starting Server
[2021-09-03 22:07:11 INFO] Version 1.17.11.01
[2021-09-03 22:07:11 INFO] Session ID 0004865f-3bfa-4b6e-9a80-0c2381f4b95a
[2021-09-03 22:07:11 INFO] Level Name: Bedrock level
[2021-09-03 22:07:11 INFO] Game mode: 0 Survival
[2021-09-03 22:07:11 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 supported, port: 19133
[INFO] IPv4 supported, port: 61096
[INFO] IPv6 supported, port: 61097
set command Registry 00000221A7E61F30
set commandRegistry
init commandRegistry
begin register command
register command lang
register command apicfg
register command tick
register command prof
register command mspt
register command test
register command backup
register command hsa
register command draw
register command village
register command counter
register command o
register command s
register command c
register command slime
register command func
register command self
register command here
register command l
register command os
register command cl
register command td?
set command stop level to gameMaster
set command whitelist level to gameMaster
[INFO] Server started.
init level obj
init server level
mod init
init thread pool
set command permission info
create backup folder
init block map
register command fakeplayer
[INFO] Trapdoor init finish,Server Start
```

**Comment by snfcx** [comment]
使用的是Xenos64
dll版本为trapdoor-0.9.73-1.17.11.01-test-3.dll
用管理员运行的
请问可能是什么原因导致没有注入成功

**Comment by hhhxiao** [comment]
没理由不成功啊，你把鼠标放到控制台最后回车试试？

**Comment by snfcx** [comment]
![image](https://user-images.githubusercontent.com/55078254/132955216-7fd5fdb5-864f-4607-b96a-824c2b5078a6.png)

**Comment by hhhxiao** [comment]
不是，就挺神奇的，我还没遇到过这个bug

**Comment by hhhxiao** [comment]
完整的控制台信息发一下呢，不要截图，从第一行到最后一行的

**Comment by snfcx** [comment]
Active code page: 65001
TRAPDOOR LOGGER INIT

  _______                  _
 |__   __|                | |
    | |_ __ __ _ _ __   __| | ___   ___  _ __
    | | '__/ _` | '_ \ / _` |/ _ \ / _ \| '__|
    | | | | (_| | |_) | (_| | (_) | (_) | |
    |_|_|  \__,_| .__/ \__,_|\___/ \___/|_|
                | |
                |_|

github:https://github.com/hhhxiao/TrapDoor
License: GPL
trapdoor version: 0.9.73-1.17.11.01-test
build time:     Sep  2 2021      13:58:41
-----------------------------------------------
begin read config file plugins/trapdoor/trapdoor-config.json
read config file plugins/trapdoor/trapdoor-config.json successfully

begin read EULA
read eula success
begin read command permission info
 - /apicfg    enable:1  level:1
 - /backup    enable:1  level:1
 - /c         enable:1  level:1
 - /cl        enable:1  level:0
 - /counter   enable:1  level:1
 - /dev       enable:1  level:1
 - /draw      enable:1  level:0
 - /fakeplayer enable:1  level:1
 - /func      enable:1  level:1
 - /here      enable:1  level:0
 - /hsa       enable:1  level:0
 - /l         enable:1  level:1
 - /lang      enable:1  level:1
 - /mspt      enable:1  level:0
 - /o         enable:1  level:1
 - /os        enable:1  level:0
 - /prof      enable:1  level:0
 - /rs        enable:1  level:1
 - /s         enable:1  level:1
 - /self      enable:1  level:0
 - /slime     enable:1  level:0
 - /spawn     enable:1  level:0
 - /td?       enable:1  level:0
 - /tick      enable:1  level:1
 - /village   enable:1  level:0
read command permission info successfully

begin read low level vanilla command info
here are the all low level commands:
- stop
- whitelist
read low level vanilla commands successfully

begin read server info
 - levelMame : Bedrock level
read server info successfully

begin read village config info
 - bound color: red
 - spawn color: red
 - poiQueryColor: red
 - center:minecraft:heart_particle
read village color successfully

begin read function config
read function config successfully

begin read self command config
read self command config successfully

create BDS mod instance
NO LOG FILE! - setting up server logging...
[2021-09-12 00:47:41 INFO] Starting Server
[2021-09-12 00:47:41 INFO] Version 1.17.11.01
[2021-09-12 00:47:41 INFO] Session ID 52815ec1-4e23-408e-9c78-4d9eef8b6775
[2021-09-12 00:47:41 INFO] Level Name: Bedrock level
[2021-09-12 00:47:41 INFO] Game mode: 0 Survival
[2021-09-12 00:47:41 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 19132
[INFO] IPv6 supported, port: 19133
[INFO] IPv4 supported, port: 60009
[INFO] IPv6 supported, port: 60010
[INFO] Server started.

Unknown command: . Please check that the command exists and that you have permission to use it.

Unknown command: . Please check that the command exists and that you have permission to use it.

Unknown command: . Please check that the command exists and that you have permission to use it.

**Comment by hhhxiao** [comment]
我没发现问题啊，挺神奇的，暂时无法解决，要不你先用旧版吧，十分抱歉（（

**Comment by snfcx** [comment]
好的，谢谢你！我明天再试试看。

**Comment by snfcx** [comment]
顺便问一下哪里可以下载到1.16.4的服务端？官网只可以下载到最新的1.17.11.01

**Comment by hhhxiao** [comment]
你直接把下载链接改成对应的版本号就行了，注意小版本也要对上
