### ISSUE TITLE
注入1.17.40的相关问题

### ISSUE THREAD

**Issue by jiangyan03** [hhhxiao/TrapDoor#62]
1 self chunk 激活后无法显示区块显示
2 hsa中下界堡垒刷怪点无法显示（其他可以显示）
3 当在地狱的时候，使用here，所在地狱的坐标成为了主世界坐标。

**Comment by hhhxiao** [comment]
emm你是本地服务器还是服务器玩家

**Comment by jiangyan03** [comment]
服务器玩家

**Comment by hhhxiao** [comment]
1可以询问腐竹是否关闭self功能
2 3需要进一步的测试，希望能提供相关截图

**Comment by hhhxiao** [comment]
已确定是bug，在修了

**Comment by jiangyan03** [comment]
我就是腐竹啊，啊哈哈哈，谢谢学姐能够支持修复

**Comment by hhhxiao** [comment]
cecf9dd88ed9922bd7822356be00fdcc8cde9094 已经在1.18.2版本中修复了这个bug，旧版懒得修了（

**Comment by jiangyan03** [comment]
啊这，主要是我长期玩1.17.40了，1.18以上版本不想动.主要地狱堡垒不显示的错误能修就行，其他的倒是没啥重要

**Comment by jiangyan03** [comment]
我修正一下bug1，区块显示在主世界可以用，在末地和地狱1失效

**Comment by jiangyan03** [comment]
是不是加载器的问题，我看了一下以前的，发现也是这个
我的加载器是LiteLoaderBDS 1.2.5，属于是1.17.40的版本加载器
hook :Explosion_explode_5adcea90
hook :BlockSource_updateNeighborsAt_4c3f8cf7
hook :HopperBlockActor_setItem_c0e5f3ce
hook :Village_tick_2a1ecbf8
hook :ServerLevel_tick_86efb826
hook :Dimension_tick_39d89862
hook :LevelChunk_tick_9d729ccd
hook :LevelChunk_tickBlocks_66280c26
hook :LevelChunk_tickBlockEntities_41f9b2ca
hook :BlockTickingQueue_tickPendingTicks_e4625213
hook :Dimension_tickRedstone_c8a7e6e5
hook :Level_tickEntitySystems_251e10ba
hook :CircuitSceneGraph_processPendingAdds_9d2954e5
hook :CircuitSceneGraph_removeComponent_1f06081d
hook :Actor_tick_8589defc
hook :Spawner_spawnStructureMob_98a1693e
hook :Item_useOn_35e33f80
hook :CommandRegistry_registerCommand_8574de98
hook :ServerNetworkHandler_handle_1a4c2996

**Comment by jiangyan03** [comment]
如果是就不麻烦你了，我关了这次问题吧

**Comment by hhhxiao** [comment]
不是，我知道问题在哪，actor.getdimensionid这个函数的偏移量错了，我手头没有相关ida文件没法修

**Comment by hhhxiao** [comment]
1.17的ida文件我已经删了

**Comment by jiangyan03** [comment]
好的，辛苦了
