### ISSUE TITLE
1.17.10.04莫名崩服

### ISSUE THREAD

**Issue by JunketPear** [hhhxiao/TrapDoor#64]
最近不知为何
在玩家均正常游戏甚至于无玩家在线时
都会出现崩服
崩服日志如下（用crashlogger捕获)
https://pastebin.ubuntu.com/p/8GqRFFjdsV/

**Comment by hhhxiao** [comment]
emmm，加了其它插件吗，或者说能复现吗

**Comment by JunketPear** [comment]
已在群内反馈
