### ISSUE TITLE
/village v false指令崩服

### ISSUE THREAD

**Issue by Thatlovely8523** [hhhxiao/TrapDoor#67]
服务端版本：1.18.2.03
Trapdoor版本：最新版
在游戏内使用/village v true指令打开村民信息显示后，使用/village v false尝试关闭会出现卡死，然后服务端崩掉

**Comment by hhhxiao** [comment]
方便提供存档吗，本地测试没法复现，可以发邮箱2602645221@qq.com或者加q群私聊

**Comment by Thatlovely8523** [comment]
请同意一下QQ：2515737066

**Comment by hhhxiao** [comment]
已于 7e5b7f546015c6309e7d5503057d55dfdd4200e3 中修复
