### ISSUE TITLE
指令提示

### ISSUE THREAD

**Issue by bibihool** [hhhxiao/TrapDoor#69]
希望在配置文件里被关闭的指令
不会在游戏里的聊天室出现
看上去和没关一样 o_o

**Comment by bibihool** [comment]
第69 issues ヾ(•ω•`)o

**Comment by hhhxiao** [comment]
emmm没看懂你的描述，能说详细点吗

**Comment by bibihool** [comment]
hmm比如说我在trapdoor-config.json里把
 "/tick": {
      "enable": false,
可是我在游戏里还是可以看到
![image](https://user-images.githubusercontent.com/72029878/151682697-9d42dba9-8c99-4d2f-90e2-7727895a6c8c.png)

**Comment by hhhxiao** [comment]
emmm，那可以使用吗，如果不能使用就不急，能用就马上修

**Comment by bibihool** [comment]
是不能使用可是他还是会显示在那边 ._.

**Comment by hhhxiao** [comment]
OK，那我有空修一下
感谢反馈

**Comment by hhhxiao** [comment]
其实这个不算是bug，算特性，懒得修了

**Comment by bibihool** [comment]
草
