### ISSUE TITLE
/os指令使服务端直接闪退

### ISSUE THREAD

**Issue by ke-admin** [hhhxiao/TrapDoor#71]
我也不清楚是否跟我的vps有没有关系，因为之前服务器是可以用这个指令的，但是现在换了一个服务器后开始用这个指令服务端就会直接闪退，tr文件夹里最后的日志也只有显示我输入的/os指令，之前服务器是4h8g的e5-2666v3，现在的是2h8g的i7-10700k

**Comment by jiangyan03** [comment]
我也是一样的os服务器崩溃（）版本1.18.2

**Comment by ke-admin** [comment]
> 

是的，我也是1.18.2

**Comment by hhhxiao** [comment]
收到

**Comment by hhhxiao** [comment]
使用旧版`/os`时闪退过吗

**Comment by ke-admin** [comment]
具体哪个版本不清楚，不过可能是从1.18.2第二个版本开始就有闪退了，或者本身就是1.18.2第一个版本就开始有的？

**Comment by hhhxiao** [comment]
就是有进度条的版本闪退对吧

**Comment by hhhxiao** [comment]
4ab41397b9cc99cc3bc7677b493f3f9aa8c04fba 可能修复了，但是还不肯定，你可与加群充当小白鼠

**Comment by ke-admin** [comment]
可以，我另开一个服务端测试

**Comment by ke-admin** [comment]
群号在哪里

**Comment by hhhxiao** [comment]
readme里面有个qq group

**Comment by ke-admin** [comment]
很遗憾，他还是闪退了╯▂╰
