### ISSUE TITLE
关于self中face面对方向错误

### ISSUE THREAD

**Issue by jiangyan03** [hhhxiao/TrapDoor#72]
我面对西方时候,显示是east(-x),面向东方时候west(+x).而且西东反了() ,west是(-x),east是(+x).
南北时候,面向北方是south(+z),面向南方时候是nortn(-z).南北z变化是对的）

**Comment by jiangyan03** [comment]
服务器版本1.18.2

**Comment by hhhxiao** [comment]
收到

**Comment by hhhxiao** [comment]
15b91ecf46500e9c7d0305621eba82e8092ed9f1
7aefe64b6e14a0d992cc46e985a9ae15a113543a
