### ISSUE TITLE
跳末地崩服

### ISSUE THREAD

**Issue by jiangyan03** [hhhxiao/TrapDoor#78]
我这里有两套LL相关崩服日志内容，1.18.2和1.18.12的都有，大部分都是玩家跳末地传送门的时候开始崩服。有很明显的玄学问题，有时候稳定，有时候经常崩（玩家经常跳末地）。我在这把记事本的内容发一下。

**Comment by jiangyan03** [comment]
1.18.2的报错日志显示
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function BlockSource::getExtraBlock at 0x7FF6BF78DD20  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function BlockSource::getLiquidBlock at 0x7FF6BF78E2A0  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function BuoyancyComponent::canFloat at 0x7FF6BEFB7440  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function `anonymous namespace'::tickBuoyancyComponent at 0x7FF6BEF46220  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function ??$iterate@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@$$CBV?$FlagComponent@UActorMovementTickNeededFlag@@@@V?$FlagComponent@UActorFlag@@@@VBlockPosTrackerComponent@@@@@ZV?$basic_view@VEntityId@@U?$get_t@$$CBV?$FlagComponent@UActorMovementTickNeededFlag@@@@V?$FlagComponent@UActorFlag@@@@VBlockPosTrackerComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@V23@$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$exclude_t@$$V@entt@@$$CBV?$FlagComponent@UActorMovementTickNeededFlag@@@@V?$FlagComponent@UActorFlag@@@@VBlockPosTrackerComponent@@@EntityRegistryBase@@AEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@$$CBV?$FlagComponent@UActorMovementTickNeededFlag@@@@V?$FlagComponent@UActorFlag@@@@VBlockPosTrackerComponent@@@@@ZAEBV?$basic_view@VEntityId@@U?$get_t@$$CBV?$FlagComponent@UActorMovementTickNeededFlag@@@@V?$FlagComponent@UActorFlag@@@@VBlockPosTrackerComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@2@Z at 0x7FF6BEF3C760  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function BuoyancySystem::tick at 0x7FF6BEF46020  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF6BF1C77E0  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function EntitySystems::tick at 0x7FF6BEF5FB60  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tickEntitySystems at 0x7FF6BF72A920  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tick at 0x7FF6BF729780  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerLevel::tick at 0x7FF6BEEDF1E0  [bedrock_server_mod.exe]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function THookTemplate<2929696350043286095,2929696350043286095>::_hook at 0x7FFDDE1EF230  [LiteXLoader.Js.dll]
-- At File D:\a\LiteXLoader\LiteXLoader\LiteXLoader\LiteXLoader\API\EventAPI.cpp : Line 1235 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function THookTemplate<2929696350043286095,2929696350043286095>::_hook at 0x7FFDDA476A70  [LiteXLoader.Lua.dll]
-- At File D:\a\LiteXLoader\LiteXLoader\LiteXLoader\LiteXLoader\API\EventAPI.cpp : Line 1235 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFDECCE4850  [LiteLoader.dll]
-- At File D:\a\LiteXLoader\LiteXLoader\LiteXLoader\LiteXLoader\API\EventAPI.cpp : Line 1235 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function TDHook_249ServerLevel_tick_86efb826::p at 0x7FFDE1CB4960  [trapdoor-0.10.2-1.18.2.03.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF6BF34B890  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerInstance::_update at 0x7FF6BEEB8E10  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function <lambda_58543e61c869eb14b8c48d51d3fe120b>::operator() at 0x7FF6BEEB0330  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_58543e61c869eb14b8c48d51d3fe120b> >,0> at 0x7FF6BEE985F0  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function o__realloc_base at 0x7FFDF938CD80  [ucrtbase.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BaseThreadInitThunk at 0x7FFDFA1C8350  [KERNEL32.DLL]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function RtlUserThreadStart at 0x7FFDFC547070  [ntdll.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????

**Comment by jiangyan03** [comment]
1.18.12的
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function BreakDoorAnnotationComponent::_shouldBreakDoor at 0x7FF601F1C2C0  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationComponent::obstructionCheck at 0x7FF601F289F0  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationSystemCpp::_tick at 0x7FF601E8CC20  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ??$iterate@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@@@ZV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@V23@$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$exclude_t@$$V@entt@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@EntityRegistryBase@@AEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@@@ZAEBV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@2@Z at 0x7FF601E88E40  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationSystem::tick at 0x7FF601E91A70  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_402054a1cc8ac232f46e648b3b6daed6>,void,ITickingSystem &>::_Do_call at 0x7FF601EA1700  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF60213DB80  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function EntitySystems::tick at 0x7FF601EA54B0  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tickEntitySystems at 0x7FF60278D490  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tick at 0x7FF60278C140  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerLevel::tick at 0x7FF601E2B3C0  [bedrock_server_mod.exe]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFD6820E130  [LiteLoader.dll]
-- At File (null) : Line -1450182880 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function TDHook_249ServerLevel_tick_86efb826::p at 0x7FFD6A2C4950  [trapdoor-0.10.2-1.18.12.01.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF602330830  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerInstance::_update at 0x7FF601E05610  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function <lambda_5d63f534eeadf9e385a3ddce5663beb8>::operator() at 0x7FF601DFD5F0  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5d63f534eeadf9e385a3ddce5663beb8> >,0> at 0x7FF601DE2240  [bedrock_server_mod.exe]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function o_exp at 0x7FFD85462630  [ucrtbase.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BaseThreadInitThunk at 0x7FFD86167960  [KERNEL32.DLL]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function RtlUserThreadStart at 0x7FFD8846A2D0  [ntdll.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function ???????? at 0x????????

**Comment by jiangyan03** [comment]
虽然可能日志部分内容不一致，但是大部分都是跳末地崩服。

**Comment by hhhxiao** [comment]
这个前几填和ll开发者交流过，是mj代码的问题，和tr无关，我有空问问解决方案

**Comment by jiangyan03** [comment]
好，感谢学姐！
