### ISSUE TITLE
支持1.18.30 LL2.2.0

### ISSUE THREAD

**Issue by win-researcher** [hhhxiao/TrapDoor#80]
服务端版本1.18.30 LiteLoader版本2.2.0
加载最新版Trapdoor（trapdoor-0.10.2-1.18.12.01）时会崩服
[CrashDump_20220423_11-45-16.zip](https://github.com/hhhxiao/TrapDoor/files/8546092/CrashDump_20220423_11-45-16.zip)

日志：
11:45:13 INFO [PreLoader] LLAutoUpdate.dll Injected.
11:45:13 INFO [PreLoader] [SymBol] Loading symbols from pdb...
11:45:14 INFO [PreLoader] [SymBol] Fast Dlsym Loaded <306077>
11:45:14 INFO [PreLoader] LiteLoader.dll Injected.

          _     _ _       _                    _
         | |   (_) |_ ___| |    ___   __ _  __| | ___ _ __
         | |   | | __/ _ \ |   / _ \ / _` |/ _` |/ _ \ '__|
         | |___| | ||  __/ |__| (_) | (_| | (_| |  __/ |
         |_____|_|\__\___|_____\___/ \__,_|\__,_|\___|_|

       --------   Light-Weight BDS Plugin Loader   ----------

11:45:14 INFO [LiteLoader] Loading plugins...
hook :Explosion_explode_5adcea90
hook :BlockSource_updateNeighborsAt_4c3f8cf7
hook :HopperBlockActor_setItem_c0e5f3ce
hook :Village_tick_2a1ecbf8
hook :ServerLevel_tick_86efb826
hook :Dimension_tick_39d89862
hook :LevelChunk_tick_9d729ccd
hook :LevelChunk_tickBlocks_66280c26
hook :LevelChunk_tickBlockEntities_41f9b2ca
hook :BlockTickingQueue_tickPendingTicks_e4625213
hook :Dimension_tickRedstone_c8a7e6e5
hook :Level_tickEntitySystems_251e10ba
hook :CircuitSceneGraph_processPendingAdds_9d2954e5
hook :CircuitSceneGraph_removeComponent_1f06081d
hook :Actor_tick_8589defc
hook :Spawner_spawnStructureMob_98a1693e
hook :Item_useOn_51392594
hook :CommandRegistry_registerCommand_8574de98
hook :ServerNetworkHandler_handle_1a4c2996
Active code page: 65001
[04-23 11:45:15 TRAPDOOR INFO] set language to zh_cn

  _______                  _
 |__   __|                | |
    | |_ __ __ _ _ __   __| | ___   ___  _ __
    | | '__/ _` | '_ \ / _` |/ _ \ / _ \| '__|
    | | | | (_| | |_) | (_| | (_) | (_) | |
    |_|_|  \__,_| .__/ \__,_|\___/ \___/|_|
                | |
                |_|

github:https://github.com/hhhxiao/TrapDoor
License: GPL
trapdoor version: TrapDoor-0.10.2-1.18.12.01
build time:     Feb 21 2022      15:06:41
-----------------------------------------------
11:45:15 INFO [LiteLoader] Plugin <trapdoor-0.10.2-1.18.12.01.dll> loaded
11:45:15 INFO [LiteLoader] 1 plugin(s) loaded
11:45:15 INFO [Server] Starting Server
11:45:15 INFO [Server] Version 1.18.30.04(ProtocolVersion 503) with LiteLoaderBDS 2.2.0
11:45:15 INFO [Server] Session ID 224aaee6-f3aa-4282-a2f8-230a8f4c300e
11:45:15 INFO [Server] Level Name: world
11:45:15 INFO [Server] Game mode: 0 Survival
11:45:15 INFO [Server] Difficulty: 2 NORMAL
11:45:15 INFO [Server] opening worlds/world/db

[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function BucketItem::BucketItem at 0x7FF64921D440  [bedrock_server_mod.exe]
[TrackBack] Function ItemRegistry::registerItemShared<BucketItem,short & __ptr64,enum BucketFillType> at 0x7FF6497D8D30  [bedrock_server_mod.exe]
[TrackBack] Function VanillaItems::registerItems at 0x7FF6497EF600  [bedrock_server_mod.exe]
[TrackBack] Function VanillaWorldSystems::Impl::Impl at 0x7FF6485FEB20  [bedrock_server_mod.exe]
[TrackBack] Function VanillaWorldSystems::init at 0x7FF648623AD0  [bedrock_server_mod.exe]
[TrackBack] Function VanillaGameModuleServer::configureLevel at 0x7FF64861A930  [bedrock_server_mod.exe]
[TrackBack] Function ServerInstance::initializeServer at 0x7FF648F12860  [bedrock_server_mod.exe]
[TrackBack] Function DedicatedServer::runDedicatedServerLoop at 0x7FF64859D580  [bedrock_server_mod.exe]
[TrackBack] Function DedicatedServer::start at 0x7FF6485A0020  [bedrock_server_mod.exe]
[TrackBack] Function main at 0x7FF6485D66C0  [bedrock_server_mod.exe]
[TrackBack] Function __scrt_common_main_seh at 0x7FF649D919D4  [bedrock_server_mod.exe]
[TrackBack] Function BaseThreadInitThunk at 0x7FFB28928350  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFB28FA7070  [ntdll.dll]

**Comment by hhhxiao** [comment]
Tr不支持跨版本，有空会更的

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/TrapDoor/issues/81#issuecomment-1107785542
