### ISSUE TITLE
Please release a version that supports 1.18.32.02.

### ISSUE THREAD

**Issue by ReallocAll** [hhhxiao/TrapDoor#84]
Most users are not yet using 1.18.33.02, as LiteLoader is currently adapted to 1.18.32.02
And CMakeLists.txt uses the unreleased BDS version 1.18.33.04, please fix it
Here is the SymHook.h that has been adapted to 1.18.32.02
[SymHook.h-1.18.32.02.zip](https://github.com/hhhxiao/TrapDoor/files/8702168/SymHook.h-1.18.32.02.zip)

**Comment by hhhxiao** [comment]
The 1.18.32 version of liteloader is compatible with 1.18.33 , i will release a release of 1.18.33 today. Or you can provide a pr to update 1.18.32 version

**Comment by ReallocAll** [comment]
But I noticed that some developers have already submitted pr for 1.18.33, would it be confusing to submit 1.18.32 at this point? Or maybe create a new branch, but that wouldn't be good either

**Comment by hhhxiao** [comment]
I will create a branch  1.18.32.02

**Comment by ReallocAll** [comment]
Thanks.
