### ISSUE TITLE
与Liteloader基础命令冲突

### ISSUE THREAD

**Issue by SuperLande** [hhhxiao/TrapDoor#88]
在安装本插件后，liteloader一系列基础插件无法识别，如"ll help"  "money add/set/query"等

**Comment by SuperLande** [comment]
描述有差错，是导致liteloader基础命令，插件可正常使用，但后台命令无法识别

**Comment by hhhxiao** [comment]
版本？另外本仓库不再维护，1.19+去 https://github.com/hhhxiao/trapdoor-ll

**Comment by Thomas455** [comment]
> 版本？另外本仓库不再维护，1.19+去 https://github.com/hhhxiao/trapdoor-ll

看一下#89
