### ISSUE TITLE
无法关闭区块显示

### ISSUE THREAD

**Issue by Thomas455** [hhhxiao/TrapDoor#89]
**Describe the bug**
1.19.20服务器在尝试关掉区块显示使用/hud remove chunk 时无效，输入/hud show false 也没有效果。
使用的客户端：win
求作者大大回复
![PNG图像](https://user-images.githubusercontent.com/99027424/185456897-90128776-b84f-489e-8239-288814a9c448.png)

**Comment by hhhxiao** [comment]
https://github.com/hhhxiao/trapdoor-ll 去这个仓库反馈
