### ISSUE TITLE
在内存中找不到函数：？

### ISSUE THREAD

**Issue by xianshuxianshu** [hhhxiao/TrapDoor#90]
LiteLoader-2.9.0；bedrock-server-1.19.50.02。
会出现以下问题：
19:34:39 ERROR [PreLoader] Could not find function in memory: ?getDimension@Level@@QEBAPEAVDimension@@V?$AutomaticID@VDimension@@H@@@Z
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll
19:34:39 ERROR [PreLoader] Could not find function in memory: ?getRotation@Actor@@QEBA?AVVec2@@XZ
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll
19:34:39 ERROR [PreLoader] Could not find function in memory: ??$parse@PEBVBlock@@@CommandRegistry@@AEBA_NPEAXAEBUParseToken@0@AEBVCommandOrigin@@HAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@@Z
19:34:39 ERROR [PreLoader] Plugin: trapdoor-0.20.0-1.19.40.02.dll

**Comment by hhhxiao** [comment]
不支持1.19
