### ISSUE TITLE
you need to accept the EULA before use trapdoor mod can not read configFile, trapdoor won't be injected

### ISSUE THREAD

**Issue by MinecraftBedrockEditionSteve** [hhhxiao/TrapDoor#91]
you need to accept the EULA before use trapdoor mod
can not read configFile, trapdoor won't be injected

**Comment by hhhxiao** [comment]
这个版本不维护了，不再接受新的issue

**Comment by MinecraftBedrockEditionSteve** [comment]
好的，理解最低目前什么版本

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月26日 23:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [bedrock-dev/TrapDoor] you need to accept the EULA before use trapdoor mod can not read configFile, trapdoor won't be injected (Issue #91)


这个版本不维护了，不再接受新的issue

―
